[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
amm = "9zmQYSuFqX5DeFkR7K6D4W2HaKWvkPmaGrVrgMTQqFDw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
